name: Scheduled External SFTP Poller

on:
  schedule:
    # run every hour (at minute 0)
    #- cron:  '0 * * * *'
    # run every 5 mins
    - cron:  '0/5 * * * *'

jobs:
  invoke_function:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.7"
      - run: npm ci
      - run: npm run invoke-sftp-poller
        env:
          STEDI_API_KEY: ${{secrets.STEDI_API_KEY}}
